export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USER = 'GET_USER';

export const ADD_FOLLOW = 'ADD_FLOLLOW';
export const DELETE_FOLLOW = 'DELETE_FOLLOW';
export const EDIT_FOLLOW = 'EDIT_FOLLOW';
export const INITIAL_FOLLOW = 'INITIAL_FOLLOW';

export const ADD_DESTINATION = 'ADD_DESTINATION';

export const ADD_ATTENDANCE = 'ADD_ATTENDANCE';
export const EDIT_ATTENDANCE = 'EDIT_ATTENDANCE';
export const DELETE_ATTENDANCE = 'REMOVE_ATTENDANCE';
export const INITIAL_ATTENDANCE = 'INITIAL_ATTENDANCE';